# Generated by Django 4.2.17 on 2024-12-18 18:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('ID', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('industry', models.CharField(max_length=100)),
                ('website', models.URLField()),
                ('contact_person', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('eligibility_criteria', models.TextField()),
            ],
            options={
                'db_table': 'placement_company',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('ID', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user_type', models.CharField(choices=[('student', 'Student'), ('company', 'Company'), ('placement_officer', 'Placement Officer')], max_length=20)),
                ('comment', models.TextField()),
                ('rating', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)])),
            ],
            options={
                'db_table': 'placement_feedback',
            },
        ),
        migrations.CreateModel(
            name='MockTest',
            fields=[
                ('ID', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('date', models.DateField()),
                ('link', models.URLField()),
            ],
            options={
                'db_table': 'placement_mock_test',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('ID', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('course', models.CharField(max_length=100)),
                ('grades', models.DecimalField(decimal_places=2, max_digits=4)),
                ('skills', models.TextField()),
                ('resume', models.FileField(upload_to='resumes/')),
            ],
            options={
                'verbose_name': 'Student',
                'verbose_name_plural': 'Students',
                'db_table': 'placement_student',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('ID', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('required_skills', models.TextField()),
                ('deadline', models.DateField()),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='placement.company')),
            ],
            options={
                'db_table': 'placement_job',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Interview',
            fields=[
                ('ID', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], max_length=20)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='placement.company')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='placement.job')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='placement.student')),
            ],
            options={
                'db_table': 'placement_interview',
            },
        ),
    ]
